export default () => ({
  franchiselist: [],
  users: [],
  userlist: [{ text: 'Select Benutzer', value: null }],
  franchise: [],
  classesList: [],
  classes: [],
  cars: [],
  extraCarList: [],
  logs: [],
  accounts: [],
  bookings: [],
  students: [],
  studentlist: [{ text: 'Select Schüler', value: null }],
  coursesarts: [],
  coursesList: [{ text: 'Select Kurz Art', value: null }],
  studentBookings: [],
  notes: [],
  carList: [{ text: 'Select Auto', value: null }],
  drivers: [{ text: 'Select Fahrer', value: null }],
  roles: [
    { text: 'Select Role', value: null },
    { text: 'Admin', value: 'admin' },
    { text: 'Receptionist', value: 'receptionist' },
    { text: 'Fahrer ', value: 'driver' },
  ],
  privates: [
    { text: 'Select Private', value: null },
    { text: 'Pause', value: 1 },
    { text: 'Urlaub', value: 2 },
  ],
  arts: [
    { text: 'Select Art', value: null },
    { text: 'Manual ', value: 'manual' },
    { text: 'Automatic ', value: 'automatic' },
  ],
})
